// Generated by ChatGPT
/* Write a javascript function to group title by category_name from given questions array? 
function categorise(response) {
    return result
}
*/
const input = {
    "questions": [
        {
            "id": 1,
            "title": "question 1",
            "category_name": "sports"
        },
        {
            "id": 2,
            "title": "question 2",
            "category_name": "sports"
        },
        {
            "id": 3,
            "title": "question 3",
            "category_name": "General Knowledge"
        },
        {
            "id": 4,
            "title": "question 4",
            "category_name": "General Knowledge"
        },
        {
            "id": 5,
            "title": "question 5",
            "category_name": "Geography"
        }
    ]
};

// First Approach: forEach()
// groupTitlesByCategory  => groupQuestionsByCategory
function groupTitlesByCategory(questionsArray) {
    const groupedTitles = {};

    questionsArray.forEach((question) => {
        const { category_name, title } = question;

        if (groupedTitles[category_name]) {
            groupedTitles[category_name].push(title);
        } else {
            groupedTitles[category_name] = [title];
        }
    });

    return groupedTitles;
}

const result = groupTitlesByCategory(input.questions);
console.log(result);


// Example 2:
function groupQuestionsByCategory(questionsArray) {
    const groupedQuestions = {};

    questionsArray.forEach(question => {
        const category = question.category_name;
        if (groupedQuestions.hasOwnProperty(category)) {
            groupedQuestions[category].push(question.title);
        } else {
            groupedQuestions[category] = [question.title];
        }
    });

    return groupedQuestions;
}

const groupedQuestions = groupQuestionsByCategory(input.questions);
console.log(groupedQuestions);


// Example 3; using Reduce
function groupTitlesByCategory(questions) {
    return questions.reduce((result, question) => {
        const { category_name, title } = question;
        if (!result[category_name]) {
            result[category_name] = [title];
        } else {
            result[category_name].push(title);
        }
        return result;
    }, {});
}

const groupedTitles = groupTitlesByCategory(input.questions);
console.log(groupedTitles);  